### ISSUE TITLE
NX remotecache-minio issue with zlib 

### ISSUE THREAD

**Issue by arvindnama** [NiklasPor/nx-remotecache-custom#20]
```
NX_TASKS_RUNNER<name-of-task-runner-with-nx-remotecahe-minio> npx nx run-many --target=<cache-able-target>
```
We see issue with zlib not able to unzip on every 3rd run. 
Need help with troubleshooting this : 

![image](https://github.com/NiklasPor/nx-remotecache-custom/assets/2868087/b97ca370-2f03-4324-90f5-5145f1dda16f)

**Comment by NiklasPor** [comment]
Probably starting with Node 18? The PR #18 might fix this, I'll merge this and publish a few new versions and we can see if your issue is resolved afterwards.

**Comment by NiklasPor** [comment]
Hey @arvindnama, could you check if this is fixed for you in `nx-remotecache-minio@4.2.0`?

**Comment by arvindnama** [comment]
@NiklasPor  looks to be working so far,  I will do some extensive testing on my pipelines and let you know .
But looks promising so far thank for a quick response.

**Comment by NiklasPor** [comment]
Feel free to reopen the issue if it's not fixed 👍
