### ISSUE TITLE
filterMachineId filters some required files

### ISSUE THREAD

**Issue by EvgeniyKumachev** [NiklasPor/nx-remotecache-custom#23]
Hi, while using this lib at one of the projects at work i encountered an issue when cached standalone build of nextjs app wrapped with sentry throws an error in docker, my investigation lead to the conclusion that cached build was missing files for `chalk@3.0.0` because it has `source` dir which was missing in cached build.

The issue i think is with [this function](https://github.com/NiklasPor/nx-remotecache-custom/blob/main/lib/filter-machine-id.ts#L2) but i haven't really understood what it filters overall 

For reproduction of this problem i've made an example repo
https://github.com/EvgeniyKumachev/nx-cache-repro

**Comment by NiklasPor** [comment]
https://github.com/NiklasPor/nx-remotecache-custom/pull/19

Explains why this is necessary, I thought nx had similar code in their implementation 💭

**Comment by NiklasPor** [comment]
If you upgrade to `nx >= 16.9.0` and `nx-remotecache-* >= 5.0.0` this should be fixed.
