### ISSUE TITLE
Surface duration it took to create an artifact to the runner

### ISSUE THREAD

**Issue by tom-sherman** [NiklasPor/nx-remotecache-custom#30]
Relates to https://github.com/vercel/remote-cache/issues/17

To properly report on time saved in Vercel Remote Cache, we need to know how long the cache artifact took to generate (the time the task took).

Is this something that is already provided by NX and could be passed through? Or does this require upstream changes in NX?

**Comment by tom-sherman** [comment]
> Time to create the artifact (time to execute build / lint / test)

Yes, that's right I think. See https://github.com/vercel/remote-cache/tree/main/packages/remote#store-artifact

> `duration` is the compute time to create the artifact in milliseconds

Passing an array of tasks should do it 👍

**Comment by NiklasPor** [comment]
@tom-sherman tasks are available starting at version `17.1.0`
