### ISSUE TITLE
"was not generated on this machine" behavior on Windows

### ISSUE THREAD

**Issue by LuminusDev** [NiklasPor/nx-remotecache-custom#31]
Hi!

As a result from the issue https://github.com/NiklasPor/nx-remotecache-custom/issues/26, I always see this problem, but only on Windows. The `source` file is not filtered, because the `tar` lib use only paths with slash, and the `path.join` function is dependant of the OS (and so, backslash for Windows). The source filenames can't be equal so.

Maybe we can use `path.normalize(path)` inside the filter function to be sure that we have the same system (`join` use the normalize function inside).

**Comment by NiklasPor** [comment]
#29 already solves this. I just have to merge it and release new versions~

**Comment by NiklasPor** [comment]
Fixed in `17.1.0`
