### ISSUE TITLE
Unclear use of this library?

### ISSUE THREAD

**Issue by zackarydev** [NiklasPor/nx-remotecache-custom#32]
Hi, I'm not quite sure what the point of this library is, but it seems like it might be what I need. Adding a better description in the README would be nice. 

My Q though: this essentially allows offloading the Nx cache to a third party? I.e. instead of using a local folder say within node_modules you can upload/download it from a HotStorage container somewhere?

What are the performance impacts of this library?

**Comment by NiklasPor** [comment]
Yes, it allows you to implement your own custom nx cache. I'd you're looking for implementations, packages like nx-remotecache-azure etc. should be for you.
