### ISSUE TITLE
stdin is not processed properly with nx > 17.3.0

### ISSUE THREAD

**Issue by dmitry-stepanenko** [NiklasPor/nx-remotecache-custom#37]
I've noticed that my processes stopped reacting on ctrl + c. Actually no other keys are propagated to the program anymore.

To reproduce:
1. Create an empty workspace using nx "npx create-nx-workspace@17.3.0". I used an integrated angular app called "myapp"
2. Run `nx lint myapp --skip-nx-cache`. Try to type something while the command executes or exit it using "ctrl + c". Notice it works fine
3. Now add a minimal configuration for the `nx-remotecache-azure` task runner
```
"tasksRunnerOptions": {
    "default": {
      "runner": "nx-remotecache-azure",
      "options": {
        "container": "nx-cache"
      }
    }
  },
```
4. Run `nx lint myapp --skip-nx-cache` again. Notice commands stdin stopped working and processes are not cancellable anymore

```
@dmitry-stepanenko ➜ npx nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 20.11.0
   OS     : linux-x64
   npm    : 10.2.4
   
   nx                 : 17.3.2
   @nx/js             : 17.3.2
   @nx/jest           : 17.3.2
   @nx/linter         : 17.3.2
   @nx/eslint         : 17.3.2
   @nx/workspace      : 17.3.2
   @nx/angular        : 17.3.2
   @nx/cypress        : 17.3.2
   @nx/devkit         : 17.3.2
   @nx/eslint-plugin  : 17.3.2
   @nrwl/tao          : 17.3.2
   @nx/web            : 17.3.2
   @nx/webpack        : 17.3.2
   typescript         : 5.3.3

@dmitry-stepanenko ➜ npm list nx-remotecache-azure
└── nx-remotecache-azure@17.1.1
```

**Comment by NiklasPor** [comment]
If anyone still comes across this, please check if it still appears under Nx 18+ with `nx-remotecache-*@18.0.0`
