### ISSUE TITLE
Possible support of custom cache with nx v18

### ISSUE THREAD

**Issue by OrangeTimes** [NiklasPor/nx-remotecache-custom#39]
Can we expect some support for the nx v18 shortly, since there are no breaking changes in v18 compared to v17?

**Comment by ahernd2** [comment]
Yep it would be good if this was supported. 
We did upgrade to version 18 of nx and we are seeing a lot of oddities in the caching. For example when we change library code which affects multiple projects, those projects are not rebuilding and are using the existing cache, meaning changes are not properly deployed to production. The only way to get changes on prod is to manually delete the entire cache

**Comment by NiklasPor** [comment]
`nx-remotecache-custom@18.0.0` is available
