### ISSUE TITLE
Support NX 19

### ISSUE THREAD

**Issue by kleinMaggus** [NiklasPor/nx-remotecache-custom#44]
Are there any plans to support NX 19 in the near future?

**Comment by NiklasPor** [comment]
Nx 19 support just landed:
📦 nx-remotecache-custom@19.0.0
📦 nx-remotecache-azure@19.0.0
📦 nx-remotecache-minio@19.0.0

If you have any problems with any of the new versions, feel free to open another issue. Thanks!
