### ISSUE TITLE
cache shared among others

### ISSUE THREAD

**Issue by EelcoLos** [NiklasPor/nx-remotecache-custom#45]
# Description
NX Remotecache currently builds the cache locally, hashes and stores it remotely (into the various options provided). This seems to be a personal hash, as neither CI nor other developers cache will be shown as cache you can retrieve.

# Motivation

NX' implementation of the remote cache shares the cache amongst others.
This can help when sharing a monorepo situation amongst developers. 
Or when a new developer joins the team, they don't have to run all the things locally, where a version is already available remotely
Or when a developer has a new environment.

# Suggested Implementation

This does help various situations:
* For a developer to run build and test, to be shared among other developers. Maybe there is a hash matching system?
* potentially, for CI. If you run build successfully local, it _might_(?) be used by CI? Maybe you want to have CI have a separate hashing system?

# Alternate Implementations

To use `nx-cloud` itself. This can have impact as it's closed source, and only has a limited amount of free executions.

**Comment by NiklasPor** [comment]
`nx-remotecache-custom` uses the default caching implementation by the nx runner. Cache sharing should work, given that the created hash actually matches. NX takes a lot of different variables into hashing the build, so make sure they are all the same on the different system. 

I ran this in the past inside CI and we successfully did build sharing. If that's not working for you (or everyone) anymore, that is either a bug or a misconfiguration. You also need to make sure that the different machines all have access to the same remotecache.

**Comment by NiklasPor** [comment]
I think this is more of a broad nx topic and not specific to this package. I don't know what's part of your CI configuration. If you don't have a very complex setup, I'd just recommend using a production configuration and a dev configuration and then you should be fine.

I personally use the same build configuration for multiple environments and then inject the environment variables during runtime.
