### ISSUE TITLE
Do not buffer archived cache files when storing or retrieving

### ISSUE THREAD

**Issue by minijus** [NiklasPor/nx-remotecache-custom#8]
Today both [store](https://github.com/NiklasPor/nx-remotecache-custom/blob/main/lib/create-remote-cache-store.ts#L10) and [retrieve](https://github.com/NiklasPor/nx-remotecache-custom/blob/main/lib/create-remote-cache-retrieve.ts#L43) operations read stream of archive and fully buffer it before archiving/extracting. Buffering means that whole file is read into memory. Having such implementation will produce uneven (spiky) memory consumption with upper limit way higher comparing to what it could be when working with stream directly.

This might be ok (not noticeable) for runners with only console output (lint/test), but it could quickly become an issue for caches of build runner where whole output directory is kept in cache (sometimes tens or hundreds on megabytes).

It would be great to update implementation so it would be capable working with streams of archives without buffering them. [npm/node-tar](https://github.com/npm/node-tar) (as a replacement for current `adm-zip` package) seems to support streams well.

I would be happy to contribute if no issues with this solution (or usage of `node-tar`) are seen.

**Comment by NiklasPor** [comment]
I'd gladly appreciate any PR in this direction. That sounds like a great idea.
If you wanna submit a draft I'll gladly review and test it.

Thanks a lot for the idea 🚀  Also I didn't do any performance tests yet, so I appreciate your input! When you're implementing this pay attention to whether actually the cache files are correctly retrieved, the nx cache is a bit tricky with some async operations there.

Also `npm link` works great for trying out the cache locally, happy hacking! Write me an email if you need any help or just comment down in your PR. I'll keep an open eye on this repository for the next week 👍

**Comment by NiklasPor** [comment]
Implemented this in `nx-remotecache-custom@2.0.0`. 🚀  The remote cache implementations will be updated next.
